### ISSUE TITLE
CI/CD for kubernetes cluster

### ISSUE THREAD

**Issue by Akongstad** [Akongstad/DevOps-group-p#337]
**Describe Feature**

**Task list**
- [x] Access production repository config files from action
- [x] Change deploy action to rolle update to cluster

**Comment by mikaeleythor** [comment]
- [ ] Change deploy action to build & push action
- [ ] Checkout manifests with [submodule action](https://github.com/marketplace/actions/checkout-submodules)
- [ ] Apply manifests with [kubectl action](https://github.com/actions-hub/kubectl)
- [ ] Append to CI chain after build & push

**Comment by mikaeleythor** [comment]
- [ ] Specify rolling updates in deployment manifest

**Comment by mikaeleythor** [comment]
[Tutorial for dispatch job](https://github.community/t/triggering-by-other-repository/16163/11)

see
```
on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    # - run: |
    #     curl -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
    #       -H "Accept: application/vnd.github.everest-preview+json" \
    #       -H "Content-Type: application/json" \
    #       https://api.github.com/repos/docker-sstc/docker-notify/actions/workflows/main.yml/dispatches \
    #       --data '{"ref": "master"}'
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'docker-sstc',
            repo: 'docker-notify',
            workflow_id: 'main.yml',
            ref: 'master'
          })
```

**Comment by mikaeleythor** [comment]
If dispatch job works we can close this issue

see https://github.com/mikaeleythor/itu-minitwit-ops/commit/3136a500c01e95909c0428180b9af04d576f81d5
