### ISSUE TITLE
Infrastructure as code

### ISSUE THREAD

**Issue by Akongstad** [Akongstad/DevOps-group-p#338]
**Describe Feature**
Create scripts for automating as much as possible of the process of creating and deploying to the cluster

**Task list**
- [ ] Use terraform script to create cluster on Do
- [ ] Deploy pods and services to the cluster
- [ ] Collect in a single executable script if possible

**Comment by mikaeleythor** [comment]
Look into [kubectl action](https://github.com/actions-hub/kubectl)
