### ISSUE TITLE
Build report.pdf using CI chain

### ISSUE THREAD

**Issue by Akongstad** [Akongstad/DevOps-group-p#344]
**Describe Feature**
We need an action per the project requirements, that compiles the latex files into a report.pdf file

**Task list**
- [x] Create compile-report.yml in main repo
- [x] In yml checkout submodule. Ressource: https://github.com/marketplace/actions/checkout-submodules
- [x] In yml use action package that compiles into pdf. Ressource: https://github.com/marketplace/actions/github-action-for-latex
- [x] Setup to run both with schedule daily and with dispatch. 
Ressources: Trigger workflows: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
Use git checkout action to check for changes

**Comment by Akongstad** [comment]
Workflow created in sub-module.
- Workflow compiles to pdf and creates pullrequest when changes are pushed in submodule
